### ISSUE TITLE
zapStart failed with org.zaproxy.clientapi.core.ClientApiException: java.net.ConnectException: Connection refused (Connection refused)

### ISSUE THREAD

**Issue by Lucas3oo** [double16/zap-gradle-plugin#2]
Hi

I am using version 2.10.0 of the plugin.

When I do gradle zapStart it fails  with org.zaproxy.clientapi.core.ClientApiException.
Looks like in the code you catch IOException but maybe the zaproxy client now throws ClientApiException with an IOException inside it.

Thanks
Lucas

**Comment by double16** [comment]
Fixed in 2.10.2
